// <auto-generated />
using System;
using Digital_Garage_Solutions_API.DBCONTEXT;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Digital_Garage_Solutions_API.Migrations
{
    [DbContext(typeof(DataBase))]
    partial class DataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Digital_Garage_Solutions_API.ViewModel.GarageRegistratioinViewModel", b =>
                {
                    b.Property<int>("GarageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GarageId"));

                    b.Property<string>("GAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GAlternateContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("GClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("GDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("GISActive")
                        .HasColumnType("bit");

                    b.Property<string>("GLatitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLongitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("GOpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("GServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GVehicles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GWorkingTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GarageId");

                    b.ToTable("GarageRegistration");
                });
#pragma warning restore 612, 618
        }
    }
}
